# Source - https://stackoverflow.com/q
# Posted by Gabe
# Retrieved 2025-11-28, License - CC BY-SA 4.0

name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: xt0rted/setup-dotnet@v1.5.0
      with:
        dotnet-version: 8.x.x
        owner: CrystalUM
        include-prerelease: 2.0.0-dev.x
      
    - name: Restore dependencies
      run: dotnet restore Padcher2XQ/Padcher2XQ.sln
      
    - name: Build application
      run: dotnet build Padcher2XQ/Padcher2XQ.sln --no-restore
      
    - name: Test application
      run: dotnet test Padcher2XQ/Padcher2XQ.sln --no-restore --verbosity normal
      
    - name: Publish artifacts to default path
      run: dotnet publish Padcher2XQ/Padcher2XQ.sln
      
    - name: Upload build artifacts for deployment
      uses: actions/upload-artifact@v4
      with:
        name: Application
        path: /home/runner/work/Padcher2XQ/Padcher2XQ/bin/Debug/avaloniaui8.0/publish/
